services:
  - type: web
    name: reconciler-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://reconciler-frontend.onrender.com

  - type: static
    name: reconciler-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: REACT_APP_API_URL
        value: https://reconciler-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache