services:
  - type: web
    name: reconciler-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001

  - type: static
    name: reconciler-frontend
    buildCommand: |
      cd frontend
      npm install
      CI=false npm run build
    publishPath: frontend/build
    staticPublishPath: /
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-cache