services:
  - type: web
    name: reconciler-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001

  - type: static
    name: reconciler-frontend
    buildCommand: npm run build
    publishDir: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html