services:
  - type: web
    name: reconciler-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001

  - type: static
    name: reconciler-frontend
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    publishDir: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html